### ISSUE TITLE
can‘t install rdepthmap

### ISSUE THREAD

**Issue by Ridalays** [orange-vertex/rdepthmap#1]
when I use tools to install rdepthmap， the Rstudio tells me that it can not find rdepthmap. I also tried the write your remind code to install rdepthmap ，but it doesn't work either.

**Comment by fani-ko** [comment]
Have you tried to follow the instructions here with the example?
https://github.com/orange-vertex/12_sss_workshop 

What exactly is the error?

**Comment by fani-ko** [comment]
What is the error message you get?
